"""Initial tables

Revision ID: 5df1eeb0515c
Revises: 
Create Date: 2026-07-09 16:23:36.518967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df1eeb0515c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('queue', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', 'IN_PROCESS', name='task_status_enum'), nullable=False),
    sa.Column('handled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_outbox_handled_at', 'outbox', ['handled_at'], unique=False)
    op.create_index('ix_outbox_status', 'outbox', ['status'], unique=False)
    op.create_index('ix_outbox_status_handled_at', 'outbox', ['status', 'handled_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency_enum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='payment_status_enum'), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_payments_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_payments_idempotency_key')
    )
    op.create_index('ix_payments_idempotency_key', 'payments', ['idempotency_key'], unique=False)
    op.create_index('ix_payments_payment_id', 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_payment_id', table_name='payments')
    op.drop_index('ix_payments_idempotency_key', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_outbox_status_handled_at', table_name='outbox')
    op.drop_index('ix_outbox_status', table_name='outbox')
    op.drop_index('ix_outbox_handled_at', table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
